name: wall
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - awpy
  - duckdb
  - jupyterlab
  - ipykernel
  - matplotlib
  - numpy
  - pandas
  - pillow
  - polars
  - pyarrow
  - pygame
  - pip:
      - demoparser2
